### ISSUE TITLE
No checkers pattern on scrollbar in previewer and other preview imprecisions

### ISSUE THREAD

**Issue by Anixx** [Abdelrhman-AK/WinPaletter#19] opened 2022-08-11 16:59 UTC
In the previewer the scrollbar does not reflect the "checkers" pattern that many classic color schemes (for instance, Windows 2000/XP scheme) show. This is because the pattern is defined by two different colors, not one.

![изображение](https://user-images.githubusercontent.com/1271736/184189380-21266639-90da-467a-ada2-48b19832be90.png)

Also, notice that 

* the scrollbar in the previewer has some vertical border on the right, 1px thick that the real scrollbar lacks.

* the menu border (even in 3D menus mode) is thinner in the previewer, it is 1px thick, while in real menus it is 2px thick and those of different colors:
![изображение](https://user-images.githubusercontent.com/1271736/184190486-4a92cee0-b32d-44fd-bddd-24a47e0e2125.png)

* The 3D windows border in the previewer (of Programs Container, Active Window and MessageBox but not of Inactive Window) has a grey 1px frame that does not change color with color scheme (that is, invariable):

![изображение](https://user-images.githubusercontent.com/1271736/184195169-49c6993c-792f-4ee3-893b-ae075bda17b8.png)

Also, the fonts in the previewer do not use the systemwide font smoothing settings and the window control elements (the [X], [_]) have too small font size.

**Comment by Abdelrhman-AK** [comment] 2022-08-11 22:09
I'll work on all these issues.

- To be honest about Fonts in the previewer that do not use the systemwide font smoothing settings and the window control elements (the [X], [_]) have too small font size: 

Last year, I was coding a GUI for VB.net code that mimics exactly Windows 98 GUI for fun and I ,intentionally, made the font looks pixelated (Graphics.TextRenderingHint = TextRenderingHint.SingleBitPerPixelGridFit;) and small font size.
-  I'll add a toggle to change between ClearType and Pixelated ones if anyone loves pixels styles :)

**Comment by Anixx** [comment] 2022-08-12 09:38
I have noticed that this grey frame around windows remains grey when loading Win32 (9x) color schemes and only visible on previewer. But if to load a Win3.1 scheme (such as Arizona, where it has orange color), its color in the previewer changes from grey and they affect the color of actual active windows.
![изображение](https://user-images.githubusercontent.com/1271736/184327762-671cac59-6b1d-418a-8f41-1ad9dbe401c0.png)
Orange frame here affects real windows, only active ones. But when a 9x scheme is loaded this frame is grey on previewer and does not affect real windows. Possibly, in 9x schemes the corresponding registry key is empty, so windows uses another color instead.

**Comment by Anixx** [comment] 2022-08-12 09:46
> I'll add a toggle to change between ClearType and Pixelated ones if anyone loves pixels styles :)

Definitely, a lot of people love it, but note that there are much more fonts settings there besides smoothing enabled/disabled.

For instance, there is subpixel smoothing, greyscale smoothing and no smoothing 3-way distinction, and subpixel smoothing can be RGB and BGR. And also there are more fine ClearType adjustments.

**Comment by Anixx** [comment] 2022-08-12 09:54
In a Win32 scheme the "Active color" looks grey on the palette, and shown grey on the previewer but does not appear on the actual windows:

![изображение](https://user-images.githubusercontent.com/1271736/184330735-cf404ad0-5766-41c1-bb0c-cb7f044843b3.png)

**Comment by Abdelrhman-AK** [comment] 2022-08-12 20:21
I have fixed most of them, I'll rework and revise the rest of bugs, wait for the next update
- Scrollbars depend on ButtonHighlight and ButtonFace, not scrollbar (scrollbar entry works only for Windows 9x)
- Active Border wasn't saved to register. I fixed the bug

**Comment by Anixx** [comment] 2022-08-12 20:25
In Windows 95 the pattern also was checkers-style.

**Comment by Abdelrhman-AK** [comment] 2022-08-12 21:05
Yup, I made the previewer with this style and removed the effect of "Scrollbar" on the previewer but kept its entry

**Comment by OrthodoxWindows** [comment] 2022-08-12 22:16
@Anixx 

> The 3D windows border in the previewer (of Programs Container, Active Window and MessageBox but not of Inactive Window) has a grey 1px frame that does not change color with color scheme (that is, invariable):

I feel like my issue #21 (https://github.com/Abdelrhman-AK/WinPaletter/issues/21) is partly a duplicate of what you posted (with the shading). If so, sorry for the duplicate.

**Comment by OrthodoxWindows** [comment] 2022-08-12 22:31
> > I'll add a toggle to change between ClearType and Pixelated ones if anyone loves pixels styles :)
> 
> Definitely, a lot of people love it, but note that there are much more fonts settings there besides smoothing enabled/disabled.
> 
> For instance, there is subpixel smoothing, greyscale smoothing and no smoothing 3-way distinction, and subpixel smoothing can be RGB and BGR. And also there are more fine ClearType adjustments.

I think for the previewer there is no need for very precise font smoothing parameters :)

**Comment by Anixx** [comment] 2022-08-12 22:37
Font smoothing (especially, subpixel) can look differently on different color backgrounds.

Also, potentially this program may include font chooser in the future, just like similar control panel applets in classic versions of Windows did.

**Comment by Anixx** [comment] 2022-08-12 22:39
Names and sizes of fonts for controls is technically a part of the "color scheme" and stored in the same place in registry.

**Comment by OrthodoxWindows** [comment] 2022-08-12 22:48
It seems to me that the color settings are no longer stored in _HKCU\Control Panel\Desktop\Colors_ but in _HKCU\Control Panel\Colors_ while metrics\fonts are always stored in _HKCU\Control Panel\Desktop\WindowMetrics_. There are currently two very good utilities for window metrics and fonts : https://github.com/Tatsu-syo/noMeiryoUI https://github.com/Tatsu-syo/ReMetrics (just missing system font support, like in Winaero Tweaker). The main advantage of these utilities is the support of the command line (and therefore batch scripts).

**Comment by Abdelrhman-AK** [comment] 2022-08-12 23:25
> It seems to me that the color settings are no longer stored in _HKCU\Control Panel\Desktop\Colors_ but in _HKCU\Control Panel\Colors_ while metrics\fonts are always stored in _HKCU\Control Panel\Desktop\WindowMetrics_. There are currently two very good utilities for window metrics and fonts : https://github.com/Tatsu-syo/noMeiryoUI https://github.com/Tatsu-syo/ReMetrics (just missing system font support, like in Winaero Tweaker). The main advantage of these utilities is the support of the command line (and therefore batch scripts).

I'm not focusing now on fonts/metrics.. may be in the future.
If so, I will depend on these sources

**Comment by Abdelrhman-AK** [comment] 2022-08-12 23:27
> > For instance, there is subpixel smoothing, greyscale smoothing and no smoothing 3-way distinction, and subpixel smoothing can be RGB and BGR. And also there are more fine ClearType adjustments.
> 
> I think for the previewer there is no need for very precise font smoothing parameters :)

I turned it to the same smoothing mode set by the user, not subpixel (To make it more close to the user)

**Comment by OrthodoxWindows** [comment] 2022-08-12 23:59
> 

In fact, I provided these links for Anixx.

**Comment by Abdelrhman-AK** [comment] 2022-08-13 00:13
> > I'm not focusing now on fonts/metrics.. may be in the future.
> > If so, I will depend on these sources
> 
> In fact, I provided these links for Anixx.
> It was not a request on my part.

I'm sorry, I misunderstood this

**Closed** 2022-08-13 19:53 UTC
